FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY apiEncryptionKey.jks apiEncryptionKey.jks
COPY ["UnlimitedJCEPolicyJDK8/", "c:\\Program Files\\Java\\jdk1.8.0_131\\jre\\lib\\security\\"]
COPY target/photo-app-api-config-server-0.0.1-SNAPSHOT.jar ConfigServer.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","ConfigServer.jar"]
